name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  ci:
    runs-on: ubuntu-latest

    name: AMO

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '12'

    - name: Install npm dependencies
      run: npm ci

    - name: Transpile code
      run: npm run build

    - name: Lint extension
      run: web-ext lint --source-dir ./extension

    - name: Build extension
      run: web-ext build --source-dir ./extension --filename easyfundraising-lite

    - name: Publish extension
      run: web-ext sign --api-key "${AMO_JWT_ISSUER}" --api-secret "${AMO_JWT_SECRET}"
      env:
        AMO_JWT_ISSUER: ${{ secrets.AMO_JWT_ISSUER }}
        AMO_JWT_SECRET: ${{ secrets.AMO_JWT_SECRET }}

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "web-ext-artifacts/*.xpi"
        generateReleaseNotes: true
        artifactContentType: application/zip
