name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  ci:
    runs-on: ubuntu-latest

    name: AMO

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
     uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install npm dependencies
      run: npm ci

    - name: Transpile code
      run: npm run build

    - name: Lint extension
      run: npm run lint:firefox

    - name: Publish extension
      run: npm run publish:firefox -- --timeout 300000
      env:
        AMO_JWT_ISSUER: ${{ secrets.AMO_JWT_ISSUER }}
        AMO_JWT_SECRET: ${{ secrets.AMO_JWT_SECRET }}

    - name: Rename extension for release
      run: 'mv "web-ext-artifacts/*.xpi" "web-ext-artifacts/easyfundraising-lite.xpi"'

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "web-ext-artifacts/easyfundraising-lite.xpi"
        generateReleaseNotes: true
        artifactContentType: application/zip
